#!/bin/bash
brew cask install Caskroom/versions/visual-studio-code-insiders

cat << EOF >> ~/.bash_profile
# Add Visual Studio Code - Insiders (code-insiders)
export PATH="$PATH:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin"
EOF